### ISSUE TITLE
Clarify the intent of History.cs

### ISSUE THREAD

**Issue by vermorel** [Evernest/Evernest#48] opened 2015-01-12 15:50 UTC
The intent of the `History` data structure. Moreover, it looks like being a binary tree. Those aspects should be emphasized and clarified.

**Comment by Olxinos** [comment] 2015-01-19 00:15
I tried to document it, it is indeed a binary search tree, though it isn't an self-balancing one and that elements must be inserted in their key's order.
The first time i made that structure, i made it in C++ with a bunch of optimization/improvement ideas in mind, now i'm not really sure that they really are worth it.
Anyway, i close the issue. Feel free to reopen it if that structure is bugging you.

**Closed by Olxinos** 2015-01-19 00:15 UTC
Labels: EvernestBack

**Comment by vermorel** [comment] 2015-01-19 06:49
OK, but you might be reinventing the wheel, I suggest to check built-in collections such as http://msdn.microsoft.com/en-us/library/dd412070%28v=vs.110%29.aspx

**Comment by Olxinos** [comment] 2015-01-19 10:54
In its current state, i surely am since its only a bit faster than a std::map for insertions (in fact, if std::map were available in C# i would have picked a std::map).
But in C#, i didn't find any satisfying data structure, i absolutely want the equivalent of the std::map::lower_bound and std::map::upper_bound ( http://www.sgi.com/tech/stl/Map.html ) which are fast and natural when using a binary search tree.

In fact, i periodically insert a pair (id, the_position_to_read_in_the_server) in this structure, but not for all ids (the structure would grow a bit too fast). Then, when i want to retrieve an event with a specific id, i look for the greatest position of lesser ids (lower_bound) and the least position of greater ids (greater_bound), i ask the server to send me the corresponding range of bytes, and i simply make a linear search in that range (i'd like to do more but having no guarantee on the size of the events, that's all i can do).

I could mimic upper_bound/lower_bound with any data structure with Enumerable.First<TSource>(IEnumerable<TSource>, Func<TSource, Boolean>) the problem is it seems to powerfull to be implemented efficiently (it's the first according to some function from TSource to the booleans and you can't guess its result unless you test it on all the elements of the set). If those data structures will make a linear search to give me what i want, i could as well not use them at all.

Oddly enough, i didn't find any binary search tree (or whatever else since they usually hide the algorithms, which may be good, but i'd like at least some information on the performance of such functions) providing the methods of my dreams in the msdn. The best i could find was a third party library (abandoned since 2011 that i can't find anymore) and posts about "how Dictionary usually replaces the std::map" or "how to mimic those methods with reasonable linear complexity".
As i was thinking that not only my data structure was faster than anything i find could in the msdn (for my needs) but i could also improve it, i thought that would be a better idea to translate it from C++ to C# (especially since it's not as complicated as a self-balancing tree).
